# Generated by Django 3.0.7 on 2020-06-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses_Students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('course_tutor_fname', models.CharField(max_length=50)),
                ('course_tutor_lname', models.CharField(max_length=50)),
                ('course_category', models.CharField(max_length=50)),
                ('course_date_start', models.DateTimeField(max_length=50)),
                ('course_duration', models.FloatField()),
                ('course_payment', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='students',
            old_name='course',
            new_name='occupation',
        ),
        migrations.RemoveField(
            model_name='students',
            name='enrollment_date',
        ),
    ]
