# Generated by Django 3.0.7 on 2020-06-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses_Students', '0002_auto_20200608_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsEnrollsToCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.DateTimeField()),
                ('enrolls_to_courses', models.ManyToManyField(to='Courses_Students.Students')),
            ],
        ),
    ]
