# Generated by Django 3.0.7 on 2020-06-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses_Students', '0003_studentsenrollstocourses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsenrollstocourses',
            name='name',
        ),
        migrations.AlterField(
            model_name='studentsenrollstocourses',
            name='enrolls_to_courses',
            field=models.ManyToManyField(to='Courses_Students.Courses'),
        ),
    ]
