# Generated by Django 3.0.7 on 2020-06-09 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses_Students', '0005_auto_20200609_0441'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentsEnrollsToCourses',
        ),
    ]
