# Generated by Django 3.0.7 on 2020-06-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses_Students', '0006_delete_studentsenrollstocourses'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsEnrollsToCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enrolled', models.DateField(auto_now_add=True)),
                ('enrolls_to_courses', models.ManyToManyField(blank=True, to='Courses_Students.Courses')),
            ],
        ),
    ]
