# Generated by Django 3.0.7 on 2020-06-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses_Students', '0008_auto_20200609_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsenrollstocourses',
            name='date_enrolled',
            field=models.CharField(max_length=50),
        ),
    ]
