# Generated by Django 3.0.7 on 2020-06-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses_Students', '0009_auto_20200609_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsenrollstocourses',
            name='date_enrolled',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
