# Generated by Django 3.0.7 on 2020-06-09 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses_Students', '0010_auto_20200609_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsenrollstocourses',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
