# Generated by Django 3.0.7 on 2020-06-10 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses_Students', '0013_courses_belongs_to_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='belongs_to_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Courses_Students.CourseCategory'),
        ),
    ]
