# Generated by Django 3.0.7 on 2020-06-11 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses_Students', '0015_auto_20200611_0331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='course_category',
        ),
    ]
