# Generated by Django 3.0.7 on 2020-06-11 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses_Students', '0016_remove_courses_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsenrollstocourses',
            name='stud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_set', to='Courses_Students.Students'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='belongs_to_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_set', to='Courses_Students.CourseCategory'),
        ),
        migrations.AlterField(
            model_name='studentsenrollstocourses',
            name='enrolls_to_courses',
            field=models.ManyToManyField(null=True, to='Courses_Students.Courses'),
        ),
    ]
