# Generated by Django 3.0.7 on 2020-06-12 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses_Students', '0021_auto_20200612_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='user',
        ),
    ]
