# Generated by Django 3.0.7 on 2020-06-12 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses_Students', '0022_remove_students_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='belongs_to_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_set', to='Courses_Students.CourseCategory'),
        ),
        migrations.AlterField(
            model_name='studentsenrollstocourses',
            name='stud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_set', to='Courses_Students.Students'),
        ),
    ]
